providers = ["python", "node"]

# Ensure both runtimes are present and ffmpeg for audio
[phases.setup]
nixPkgs = ["python312", "nodejs_20", "ffmpeg"]

# Build the Next.js app during the build phase
[phases.build]
commands = [
  "cd youtube-summarizer-ui && npm install --no-audit --no-fund",
  "cd youtube-summarizer-ui && npm run build",
]

# Start both backend (uvicorn) and frontend (Next.js) via our script
[start]
cmd = "bash start.sh"

