# Railway config-as-code for Backend (FastAPI)

[build]
builder = "nixpacks"
watchPatterns = [
  "app.py",
  "youtube_summarizer/**",
  "requirements.txt",
  "pyproject.toml",
]

[build.nixpacksPlan]
providers = ["python"]

[build.nixpacksPlan.phases.setup]
# System packages required at runtime
nixPkgs = ["ffmpeg"]

[deploy]
# Bind to the port provided by Railway
startCommand = "uvicorn app:app --host 0.0.0.0 --port ${PORT:-8080}"
healthcheckPath = "/test"
healthcheckTimeout = 300
restartPolicyType = "always"
overlapSeconds = 20
drainingSeconds = 10

# Optional environment-specific overrides (example)
[environments.staging.deploy]
startCommand = "uvicorn app:app --host 0.0.0.0 --port ${PORT:-8080} --reload"


